//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanoramaApp1.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSentence {
            get {
                return ResourceManager.GetString("AboutSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string AndConjuntion {
            get {
                return ResourceManager.GetString("AndConjuntion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about app.
        /// </summary>
        public static string ApBar_AboutButtonText {
            get {
                return ResourceManager.GetString("ApBar_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmi history.
        /// </summary>
        public static string ApBar_HistoryButtonText {
            get {
                return ResourceManager.GetString("ApBar_HistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit&amp;Gym.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate BMI.
        /// </summary>
        public static string BMICalculatatorExecuteButtonText {
            get {
                return ResourceManager.GetString("BMICalculatatorExecuteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string BMICalculatatorHeightLabelValue {
            get {
                return ResourceManager.GetString("BMICalculatatorHeightLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your height in cm....
        /// </summary>
        public static string BMICalculatatorHeightTextboxDefaultValue {
            get {
                return ResourceManager.GetString("BMICalculatatorHeightTextboxDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string BMICalculatatorWeightLabelValue {
            get {
                return ResourceManager.GetString("BMICalculatatorWeightLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your weight in kg....
        /// </summary>
        public static string BMICalculatatorWeightTextboxDefaultValue {
            get {
                return ResourceManager.GetString("BMICalculatatorWeightTextboxDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI Calculator.
        /// </summary>
        public static string BMICalculatorPanoramaHeaderText {
            get {
                return ResourceManager.GetString("BMICalculatorPanoramaHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height - incorrect value.
        /// </summary>
        public static string BMIHeightInvalidInputException {
            get {
                return ResourceManager.GetString("BMIHeightInvalidInputException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height value should be between.
        /// </summary>
        public static string BMIHeightInvalidRangeException {
            get {
                return ResourceManager.GetString("BMIHeightInvalidRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is empty... so far.
        /// </summary>
        public static string BMIHistoryIsEmptyPlaceholder {
            get {
                return ResourceManager.GetString("BMIHistoryIsEmptyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of your BMI.
        /// </summary>
        public static string BMIHistoryWindowTitle {
            get {
                return ResourceManager.GetString("BMIHistoryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very severely underweight.
        /// </summary>
        public static string BMILimitLvl_0 {
            get {
                return ResourceManager.GetString("BMILimitLvl_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severely underweight.
        /// </summary>
        public static string BMILimitLvl_1 {
            get {
                return ResourceManager.GetString("BMILimitLvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        public static string BMILimitLvl_2 {
            get {
                return ResourceManager.GetString("BMILimitLvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal weight.
        /// </summary>
        public static string BMILimitLvl_3 {
            get {
                return ResourceManager.GetString("BMILimitLvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        public static string BMILimitLvl_4 {
            get {
                return ResourceManager.GetString("BMILimitLvl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderately obese.
        /// </summary>
        public static string BMILimitLvl_5 {
            get {
                return ResourceManager.GetString("BMILimitLvl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severely obese.
        /// </summary>
        public static string BMILimitLvl_6 {
            get {
                return ResourceManager.GetString("BMILimitLvl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very severely obese.
        /// </summary>
        public static string BMILimitLvl_7 {
            get {
                return ResourceManager.GetString("BMILimitLvl_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight - incorrect value.
        /// </summary>
        public static string BMIWeightInvalidInputException {
            get {
                return ResourceManager.GetString("BMIWeightInvalidInputException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight value should be between.
        /// </summary>
        public static string BMIWeightInvalidRangeException {
            get {
                return ResourceManager.GetString("BMIWeightInvalidRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szbartnik@gmail.com.
        /// </summary>
        public static string CreatorEmail {
            get {
                return ResourceManager.GetString("CreatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szymon Bartnik.
        /// </summary>
        public static string CreatorNameAndSurname {
            get {
                return ResourceManager.GetString("CreatorNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and created by.
        /// </summary>
        public static string DesignedAndCreatedBySentence {
            get {
                return ResourceManager.GetString("DesignedAndCreatedBySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
