//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoramaApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanoramaApp1.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutSentence {
            get {
                return ResourceManager.GetString("AboutSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string AndConjuntion {
            get {
                return ResourceManager.GetString("AndConjuntion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about app.
        /// </summary>
        public static string ApBar_AboutButtonText {
            get {
                return ResourceManager.GetString("ApBar_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bmi history.
        /// </summary>
        public static string ApBar_HistoryButtonText {
            get {
                return ResourceManager.GetString("ApBar_HistoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI Calc.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate BMI.
        /// </summary>
        public static string BMICalculatatorExecuteButtonText {
            get {
                return ResourceManager.GetString("BMICalculatatorExecuteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string BMICalculatatorHeightLabelValue {
            get {
                return ResourceManager.GetString("BMICalculatatorHeightLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your height in cm....
        /// </summary>
        public static string BMICalculatatorHeightTextboxDefaultValue {
            get {
                return ResourceManager.GetString("BMICalculatatorHeightTextboxDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string BMICalculatatorWeightLabelValue {
            get {
                return ResourceManager.GetString("BMICalculatatorWeightLabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your weight in kg....
        /// </summary>
        public static string BMICalculatatorWeightTextboxDefaultValue {
            get {
                return ResourceManager.GetString("BMICalculatatorWeightTextboxDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height - incorrect value.
        /// </summary>
        public static string BMIHeightInvalidInputException {
            get {
                return ResourceManager.GetString("BMIHeightInvalidInputException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height value should be between.
        /// </summary>
        public static string BMIHeightInvalidRangeException {
            get {
                return ResourceManager.GetString("BMIHeightInvalidRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History is empty... so far.
        /// </summary>
        public static string BMIHistoryIsEmptyPlaceholder {
            get {
                return ResourceManager.GetString("BMIHistoryIsEmptyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History of your BMI.
        /// </summary>
        public static string BMIHistoryWindowTitle {
            get {
                return ResourceManager.GetString("BMIHistoryWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very severely underweight.
        /// </summary>
        public static string BMILimitLvl_0 {
            get {
                return ResourceManager.GetString("BMILimitLvl_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you definitely should see your GP. It is very important to do not ignore symptoms.
        ///
        ///If you ignore your unambiguous BMI results your health will be critically threatened..
        /// </summary>
        public static string BMILimitLvl_0_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_0_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severely underweight.
        /// </summary>
        public static string BMILimitLvl_1 {
            get {
                return ResourceManager.GetString("BMILimitLvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are severly underweight which means you should seriously think about seeing your GP. 
        ///
        ///Of course you should eat more because your current BMI indicates that you might have some problems with your organism in the near future..
        /// </summary>
        public static string BMILimitLvl_1_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_1_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        public static string BMILimitLvl_2 {
            get {
                return ResourceManager.GetString("BMILimitLvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are underweight, which can affect health.
        ///
        ///Try to eat more..
        /// </summary>
        public static string BMILimitLvl_2_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_2_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal weight.
        /// </summary>
        public static string BMILimitLvl_3 {
            get {
                return ResourceManager.GetString("BMILimitLvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggest you are a healthy weight for your height.
        ///
        ///Maintaining a healthy weight decreases the risk of a range of serious health problems..
        /// </summary>
        public static string BMILimitLvl_3_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_3_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        public static string BMILimitLvl_4 {
            get {
                return ResourceManager.GetString("BMILimitLvl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are overweight, which increases the risk of becoming ill with problems such as high blood pressure, heart disease and cancer.
        ///
        ///You should think about doing sports and changing your diet to be fit..
        /// </summary>
        public static string BMILimitLvl_4_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_4_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderately obese.
        /// </summary>
        public static string BMILimitLvl_5 {
            get {
                return ResourceManager.GetString("BMILimitLvl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are obese, which increases the risk of becoming ill with problems such as high blood pressure, heart disease and cancer.
        ///
        ///You should think about seeing your GP and definitely start doing sports and/or changing your current diet..
        /// </summary>
        public static string BMILimitLvl_5_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_5_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severely obese.
        /// </summary>
        public static string BMILimitLvl_6 {
            get {
                return ResourceManager.GetString("BMILimitLvl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are at 2nd stadium of obesity which increases the risk of becoming ill with problems such as high blood pressure, heart disease and cancer.
        ///
        ///You definitely should see your GP and change your diet because your health is threatened..
        /// </summary>
        public static string BMILimitLvl_6_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_6_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very severely obese.
        /// </summary>
        public static string BMILimitLvl_7 {
            get {
                return ResourceManager.GetString("BMILimitLvl_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result suggests you are at 3rd stadium of obesity which increases the risk of becoming ill with problems such as high blood pressure, heart disease and cancer.
        ///
        ///You definitely should see your GP and change your diet because your health is threatened.
        ///
        ///Your current lifestyle is unhealthy and you shouldn&apos;t ignore this..
        /// </summary>
        public static string BMILimitLvl_7_Info {
            get {
                return ResourceManager.GetString("BMILimitLvl_7_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight - incorrect value.
        /// </summary>
        public static string BMIWeightInvalidInputException {
            get {
                return ResourceManager.GetString("BMIWeightInvalidInputException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight value should be between.
        /// </summary>
        public static string BMIWeightInvalidRangeException {
            get {
                return ResourceManager.GetString("BMIWeightInvalidRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to szbartnik@gmail.com.
        /// </summary>
        public static string CreatorEmail {
            get {
                return ResourceManager.GetString("CreatorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szymon Bartnik.
        /// </summary>
        public static string CreatorNameAndSurname {
            get {
                return ResourceManager.GetString("CreatorNameAndSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed and created by.
        /// </summary>
        public static string DesignedAndCreatedBySentence {
            get {
                return ResourceManager.GetString("DesignedAndCreatedBySentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
